name: Publish to NPM

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@hagateway'
          cache: 'npm'

      # TODO !!!!!
      - name: Install dependencies
        run: |
          sudo apt-get install --yes libpam0g-dev
          npm install

      - name: Publish packages
        run: |
          npm publish --workspaces --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
